"""Generate downloadable analysis reports as TXT and PDF."""
from __future__ import annotations

import io
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (ListFlowable, ListItem, Paragraph,
                                SimpleDocTemplate, Spacer, Table, TableStyle)


def _as_list(value) -> list[str]:
    if isinstance(value, list):
        out = []
        for item in value:
            if isinstance(item, dict):
                out.append(
                    item.get("message")
                    or item.get("word")
                    or item.get("skill")
                    or ", ".join(str(v) for v in item.values()))
            else:
                out.append(str(item))
        return out
    if value in (None, ""):
        return []
    return [str(value)]


def build_txt(analysis: dict) -> bytes:
    result = analysis.get("result", {})
    lines: list[str] = []
    add = lines.append

    add("=" * 60)
    add("AI RESUME ANALYZER - REPORT")
    add("=" * 60)
    add(f"Resume : {analysis.get('resume_name', 'N/A')}")
    add(f"Role   : {analysis.get('job_role', 'N/A')}")
    add(f"Date   : {analysis.get('created_at', datetime.utcnow())}")
    add("")

    add("SCORES")
    add("-" * 60)
    score_keys = [
        ("Overall Score", "overall_score"),
        ("ATS Score", "ats_score"),
        ("Technical Skills", "technical_skills_score"),
        ("Soft Skills", "soft_skills_score"),
        ("Experience", "experience_score"),
        ("Education", "education_score"),
        ("Projects", "project_score"),
        ("Formatting", "formatting_score"),
        ("Grammar", "grammar_score"),
        ("Keyword Match", "keyword_match"),
    ]
    for label, key in score_keys:
        add(f"  {label:<20}: {result.get(key, 0)}/100")
    add(f"  {'Career Level':<20}: {result.get('career_level', 'N/A')}")
    add(f"  {'Industry Readiness':<20}: "
        f"{result.get('industry_readiness', 'N/A')}")
    add("")

    sections = [
        ("STRENGTHS", "strengths"),
        ("WEAKNESSES", "weaknesses"),
        ("MISSING SKILLS", "missing_skills"),
        ("MISSING KEYWORDS", "missing_keywords"),
        ("IMPROVEMENT SUGGESTIONS", "improvement_suggestions"),
        ("FORMATTING ISSUES", "formatting_issues"),
    ]
    for title, key in sections:
        items = _as_list(result.get(key))
        if not items:
            continue
        add(title)
        add("-" * 60)
        for it in items:
            add(f"  - {it}")
        add("")

    gap = result.get("skills_gap", {})
    if gap.get("roadmap"):
        add("LEARNING ROADMAP")
        add("-" * 60)
        for step in gap["roadmap"]:
            add(f"  - {step.get('skill')}: {step.get('action')}")
        add("")

    add("Reviews")
    add("-" * 60)
    for label, key in (("Summary", "professional_summary_review"),
                       ("Projects", "project_review"),
                       ("Achievements", "achievements_review"),
                       ("Length", "resume_length_review")):
        add(f"  {label}: {result.get(key, 'N/A')}")
    add("")
    add("Generated by AI Resume Analyzer")
    return ("\n".join(lines)).encode("utf-8")


def build_pdf(analysis: dict) -> bytes:
    result = analysis.get("result", {})
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        leftMargin=18 * mm, rightMargin=18 * mm,
        topMargin=16 * mm, bottomMargin=16 * mm,
        title="AI Resume Analyzer Report",
    )
    styles = getSampleStyleSheet()
    h1 = ParagraphStyle("h1", parent=styles["Heading1"], fontSize=18,
                        textColor=colors.HexColor("#4f46e5"))
    h2 = ParagraphStyle("h2", parent=styles["Heading2"], fontSize=13,
                        textColor=colors.HexColor("#111827"), spaceBefore=10)
    body = ParagraphStyle("body", parent=styles["BodyText"], fontSize=10,
                          alignment=TA_LEFT, leading=14)

    flow: list = []
    flow.append(Paragraph("AI Resume Analyzer Report", h1))
    flow.append(Paragraph(
        f"Resume: <b>{analysis.get('resume_name', 'N/A')}</b> &nbsp;|&nbsp; "
        f"Role: <b>{analysis.get('job_role', 'N/A')}</b> &nbsp;|&nbsp; "
        f"Date: {analysis.get('created_at', '')}", body))
    flow.append(Spacer(1, 8))

    # Scores table.
    score_rows = [["Metric", "Score"]]
    for label, key in [
        ("Overall Score", "overall_score"), ("ATS Score", "ats_score"),
        ("Technical Skills", "technical_skills_score"),
        ("Soft Skills", "soft_skills_score"),
        ("Experience", "experience_score"),
        ("Education", "education_score"),
        ("Projects", "project_score"),
        ("Formatting", "formatting_score"),
        ("Grammar", "grammar_score"),
        ("Keyword Match", "keyword_match"),
    ]:
        score_rows.append([label, f"{result.get(key, 0)} / 100"])
    table = Table(score_rows, colWidths=[90 * mm, 40 * mm])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#4f46e5")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1),
         [colors.white, colors.HexColor("#f3f4f6")]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e5e7eb")),
        ("PADDING", (0, 0), (-1, -1), 6),
    ]))
    flow.append(table)

    flow.append(Paragraph(
        f"Career Level: <b>{result.get('career_level', 'N/A')}</b> &nbsp; | "
        f"&nbsp; Industry Readiness: "
        f"<b>{result.get('industry_readiness', 'N/A')}</b>", body))

    def bullets(title: str, key: str) -> None:
        items = _as_list(result.get(key))
        if not items:
            return
        flow.append(Paragraph(title, h2))
        flow.append(ListFlowable(
            [ListItem(Paragraph(it, body)) for it in items[:15]],
            bulletType="bullet"))

    bullets("Strengths", "strengths")
    bullets("Weaknesses", "weaknesses")
    bullets("Missing Skills", "missing_skills")
    bullets("Missing Keywords", "missing_keywords")
    bullets("Improvement Suggestions", "improvement_suggestions")
    bullets("Formatting Issues", "formatting_issues")

    gap = result.get("skills_gap", {})
    if gap.get("roadmap"):
        flow.append(Paragraph("Learning Roadmap", h2))
        flow.append(ListFlowable(
            [ListItem(Paragraph(
                f"<b>{s.get('skill')}</b>: {s.get('action')}", body))
             for s in gap["roadmap"]], bulletType="bullet"))

    flow.append(Paragraph("Reviews", h2))
    for label, key in (("Summary", "professional_summary_review"),
                       ("Projects", "project_review"),
                       ("Achievements", "achievements_review"),
                       ("Length", "resume_length_review")):
        flow.append(Paragraph(
            f"<b>{label}:</b> {result.get(key, 'N/A')}", body))

    doc.build(flow)
    return buffer.getvalue()
